spring:
  application:
    name: issue-tracker

  datasource:
    url: jdbc:mysql://localhost:3306/issue_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
